#!/usr/bin/env bash

mv ~/Documents/ViberDownloads/ ~/.Trash
cd ~/.Trash
rm -rf ViberDownloads

osascript -e 'tell application "Terminal" to close (every window whose name contains "ClearViberDownloads")' &
exit
